CREATE TABLE PERSONAS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME           VARCHAR(60) NOT NULL,
   APAT           VARCHAR(60) NOT NULL,
   AMAT           VARCHAR(60),
   FCHNAC         TEXT,
   DIRECCION      CHAR(50),
   ESTADO         CHAR(50),
   TELEFONO       CHAR(50),
   EMAIL          CHAR(50),
   RUTAFOTO       VARCHAR(255),
   IDENTIFICACIONA  VARCHAR(255),
   IDENTIFICACIONB  VARCHAR(255) 
);